In [1]:
import numpy as np # linear algebra

#Filtering = Refers to the process of selecting elements from an array that match a given condition

ages = np.array([[21,20,33,41,18,26,27,29],
                 [51,16,17,18,19,20,21,31]])

teenagers = ages[ages<18]

print(teenagers)

[16 17]


In [4]:
adults = ages[(ages>=18 )   &  (ages<50)  ]
print(adults)

[21 20 33 41 18 26 27 29 18 19 20 21 31]


In [5]:
evens = ages [ ages%2 == 0]
print(evens)

[20 18 26 16 18 20]


In [7]:
#where to preserve shape 

adults = np.where(ages>=18 , ages , -1)
print(adults)

[[21 20 33 41 18 26 27 29]
 [51 -1 -1 18 19 20 21 31]]
