In [1]:
import numpy as np

print(np.__version__)

2.3.5


In [5]:
#create array

np_array = np.array([1,2,3,4])
print(np_array)
mathsOperation = np_array * 2 #vectorized operation

print(mathsOperation)

print(type(mathsOperation))

[1 2 3 4]
[2 4 6 8]
<class 'numpy.ndarray'>


In [9]:
#dtype = tells numpy what kind of values are stored in an array otherwise numpy guesses 
#integer (int8,int16,int32,int64)

np_array = np.array([1,2,3,4,5])
print(np_array)
print(np_array.dtype)
print(f"{np_array.nbytes} bytes")

[1 2 3 4 5]
int64
40 bytes


In [10]:
np_array = np.array([1,2,3,4,5], dtype = np.int32)
print(np_array)
print(np_array.dtype)
print(f"{np_array.nbytes} bytes")

[1 2 3 4 5]
int32
20 bytes


In [11]:
np_array = np.array([1,2,3,4,5], dtype = np.int16)
print(np_array)
print(np_array.dtype)
print(f"{np_array.nbytes} bytes")

[1 2 3 4 5]
int16
10 bytes


In [13]:
#np_array = np.array([129,126], dtype = np.int8)
#print(np_array)
#print(np_array.dtype)
#print(f"{np_array.nbytes} bytes")

In [14]:
np_array = np.array([1,2,3,4,5], dtype = np.float16)
print(np_array)
print(np_array.dtype)
print(f"{np_array.nbytes} bytes")

[1. 2. 3. 4. 5.]
float16
10 bytes


In [16]:
np_array = np.array([1,2,3,4,5,0], dtype = np.bool_) #bool_ is numpy boolean 
#any non zero is true
print(np_array)
print(np_array.dtype)
print(f"{np_array.nbytes} bytes")

[ True  True  True  True  True False]
bool
6 bytes


In [18]:
np_array = np.array([1,2,3,4,5], dtype = np.str_) #str_ is numpy string 
#any non zero is true
print(np_array)
print(np_array.dtype)
print(f"{np_array.nbytes} bytes")

['1' '2' '3' '4' '5']
<U1
20 bytes


In [19]:
np_array = np.array(["apple","orange","banana"], dtype = np.str_) #str_ is numpy string 
#any non zero is true
print(np_array)
print(np_array.dtype)
print(f"{np_array.nbytes} bytes")

['apple' 'orange' 'banana']
<U6
72 bytes


In [20]:
np_array = np.array(["apple","orange","banana"], dtype = "<U4") #str_ is numpy string 
#any non zero is true
print(np_array)
print(np_array.dtype)
print(f"{np_array.nbytes} bytes")

['appl' 'oran' 'bana']
<U4
48 bytes


In [21]:
#objects

np_array = np.array(["apple",1.2,"banana"], dtype = np.object_) #object_ is python object so speed is slow
#any non zero is true
print(np_array)
print(np_array.dtype)
print(f"{np_array.nbytes} bytes")

['apple' 1.2 'banana']
object
24 bytes


In [23]:
np_array = np.array([1,2,3,4,5]) 
#any non zero is true
np_array = np_array.astype(np.float16)
print(np_array)
print(np_array.dtype)
print(f"{np_array.nbytes} bytes")

[1. 2. 3. 4. 5.]
float16
10 bytes
