In [1]:
import numpy as np # linear algebra

#reshape = changes the shape of an array w/o altering its underlying data .reshape(rows, cols) 

array2D = np.array([[1,2,3,4],
                    [5,6,7,8],
                    [9,10,11,12],
                    [13,14,15,16]]) 

#array[start : end : step]

In [2]:
print(array2D[0])

[1 2 3 4]


In [3]:
print(array2D[1])

[5 6 7 8]


In [4]:
print(array2D[0,0:2])

[1 2]


In [5]:
print(array2D[0:2,0])

[1 5]


In [7]:
print(array2D[0:4]) #getting all rows

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [9]:
print(array2D[1:3]) 

[[ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
print(array2D[0:4:2]) #getting only seconds  rows

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [11]:
print(array2D[::2]) #getting only seconds  rows or odd rows

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [12]:
print(array2D[::-2]) #getting rows in reverse order

[[13 14 15 16]
 [ 5  6  7  8]]


In [13]:
print(array2D[0,0:2]) # first is for row , second is for column

[1 2]


In [14]:
print(array2D[:,0:2]) # first is for row , second is for column
#all rows , 0-1 col

[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]


In [15]:
print(array2D[:, -2]) # first is for row , second is for column
#all rows , second last column only

[ 3  7 11 15]


In [16]:
print(array2D[0:2,0:2])

[[1 2]
 [5 6]]
