In [1]:
import numpy as np # linear algebra

#reshape = changes the shape of an array w/o altering its underlying data .reshape(rows, cols) 

array1D = np.array([1,2,3,4,5,6,7,8,9,10,11,12]) 

array_reshaped = array1D.reshape(2,6)

print(array_reshaped.shape)
print(array_reshaped)

(2, 6)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [2]:
array_reshaped = array1D.reshape(3,4)

print(array_reshaped.shape)
print(array_reshaped)

(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [3]:
array_reshaped3d = array1D.reshape(2,3,2)

print(array_reshaped3d.shape)
print(array_reshaped3d)

(2, 3, 2)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [5]:
array_reshaped2d = array1D.reshape(-1,1)#for -1 numpy will adjust automatically

print(array_reshaped2d.shape)
print(array_reshaped2d)

(12, 1)
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
