In [3]:
import numpy as np # linear algebra

#scaler arithmetic 
array = np.array([1,2,3])

print(array+1)
print(array-2)

print(array*3)
print(array / 4)
print(array**5)

[2 3 4]
[-1  0  1]
[3 6 9]
[0.25 0.5  0.75]
[  1  32 243]


In [4]:
#vectorized math function 
array = np.array([1,2,3])

print(np.sqrt(array))

[1.         1.41421356 1.73205081]


In [7]:
array = np.array([1.2,2.5,3.7])
print(np.floor(array))
print(np.ceil(array))
print(np.round(array))

[1. 2. 3.]
[2. 3. 4.]
[1. 2. 4.]


In [8]:
radius = np.array([1,2,3])

print(np.pi * radius**2) 

[ 3.14159265 12.56637061 28.27433388]


In [10]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

print(array1+array2)

print(array1-array2)

print(array1*array2)

print(array1/array2)

print(array1**array2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [11]:
#comparision operator 
scores = np.array([91,55,100,73,82,64])

print(scores >= 60)


[ True False  True  True  True  True]


In [12]:
scores = np.array([91,55,100,73,82,64])

print(scores < 60)

[False  True False False False False]


In [14]:
#scores < 60 filter condition
scores[scores < 60] = 0
print(scores)

[ 91   0 100  73  82  64]
