In [4]:
import numpy as np # linear algebra


rng = np.random.default_rng()

print(rng.integers(low=1, high=7)) # random no btw 1 and 6

2


In [5]:
print(rng.integers(low=1, high=100 , size = 3)) #3 random no btw 1 and 100

[78 91 82]


In [6]:
print(rng.integers(low=1, high=100 , size = (3,2))) #3,2 random no btw 1 and 100

[[85 92]
 [75 24]
 [34 26]]


In [8]:
print(np.random.uniform()) # random floating point between 0 and 1

0.23084381216376815


In [9]:
array = np.array([1,2,3,4,5])

print(array)

rng.shuffle(array)
print(array)

[1 2 3 4 5]
[2 5 3 1 4]


In [13]:
fruits = np.array(['apple','orange','banana','coconut','pineapple','kiwi'])

rng.choice(fruits)

np.str_('banana')

In [14]:
fruits = np.array(['apple','orange','banana','coconut','pineapple','kiwi'])

rng.choice(fruits , size=(2,3))

array([['pineapple', 'coconut', 'pineapple'],
       ['pineapple', 'orange', 'orange']], dtype='<U9')