In [1]:
import pandas as pd

df_boston = pd.read_csv('Boston House Prices.csv')

In [2]:
import statsmodels.api as sm

In [4]:
#dependent variable
y = df_boston['Value']

#independent variable 

X = df_boston[['Rooms','Distance']]

In [5]:
#adding a constant
X = sm.add_constant(X) #adding a constant
#fitting the model
lm = sm.OLS(y, X).fit() #(dependent variable , independent variable)


In [6]:
lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Value   R-squared:                       0.496
Model:                            OLS   Adj. R-squared:                  0.494
Method:                 Least Squares   F-statistic:                     247.0
Date:                Sun, 24 May 2026   Prob (F-statistic):           1.84e-75
Time:                        16:27:38   Log-Likelihood:                -1667.1
No. Observations:                 506   AIC:                             3340.
Df Residuals:                     503   BIC:                             3353.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        -34.6361      2.621    -13.212      0.000     -39.786     -29.486
Rooms          8.8014      0.424     20.780      0.000       7.969       9.634
Distance       0.4888      0.141      3.459      0.001       0.211       0.767
==============================================================================
Omnibus:                      142.807   Durbin-Watson:                   0.684
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              844.520
Skew:                           1.090   Prob(JB):                    4.12e-184
Kurtosis:                       8.942   Cond. No.                         68.7
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [7]:
from sklearn import linear_model

In [8]:
#dependent variable
y = df_boston['Value']

#independent variable 

X = df_boston[['Rooms','Distance']]

In [9]:
#Fitting the model
lm = linear_model.LinearRegression()
lm.fit(X , y ) #order has changes (independent , dependent)


,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [10]:
lm.predict(X)

array([25.23262311, 24.30597474, 31.03025338, 29.9197274 , 31.23113776,
       24.92052548, 20.99628003, 22.59515685, 17.89792552, 21.43016488,
       24.59312806, 21.29554669, 19.86012857, 20.02480328, 21.19854962,
       18.91052046, 19.79946305, 20.16587486, 15.24036623, 17.62554884,
       16.24441157, 19.82577837, 21.36632302, 18.52848931, 19.65425152,
       16.82067934, 18.81534563, 20.76312523, 24.70679323, 26.17680132,
       17.71571146, 20.84706509, 19.68285587, 17.39216584, 20.85532906,
       19.22540394, 18.42427779, 18.77543693, 19.75391977, 26.04958067,
       29.82538634, 27.7461615 , 22.45651299, 22.82617229, 21.57637181,
       17.86689491, 18.78224174, 21.21771802, 15.7523132 , 17.64542212,
       21.17812468, 22.51593928, 26.00129836, 21.48617409, 20.7648873 ,
       33.41670435, 26.03470634, 29.42393915, 23.26887906, 20.91861579,
       19.42498135, 21.20638654, 25.71803969, 28.7805479 , 32.39778062,
       23.95685233, 19.52974218, 20.27518634, 17.77558538, 20.33

In [12]:
lm.predict(X)[0:5]

array([25.23262311, 24.30597474, 31.03025338, 29.9197274 , 31.23113776])

Regression Table 

In [13]:
#r squared score
lm.score(X , y)

0.4955246476058477

In [14]:
# coefficient

lm.coef_

array([8.80141183, 0.48884854])

In [15]:
#intercept
lm.intercept_

np.float64(-34.636050175473315)